spring.application.name=bookingservice

spring.datasource.mysql.jdbc-url=${MYSQL_DATABASE_URL}
spring.datasource.mysql.username=${MYSQL_DATABASE_NAME}
spring.datasource.mysql.password=${MYSQL_DATABASE_PASSWORD}
spring.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.postgres.jdbc-url=${POSTGRES_DATABASE_URL}
spring.datasource.postgres.username=${POSTGRES_DATABASE_NAME}
spring.datasource.postgres.password=${POSTGRES_DATABASE_PASSWORD}
spring.datasource.postgres.driver-class-name=org.postgresql.Driver


app.generator.workerId=1
app.generator.datacenterId=1
